In [1]:
import sys
import py_entitymatching as em
import pandas as pd
import os

In [9]:
walmart=pd.read_csv('csv_files/walmart_short.csv', dtype = {'custom_id':int})
walmart.fillna({'brand':'',
                'modelno':'',
                'title':'',
                'price':0,
                'descr':'',
                'dimensions':'',
                'shipweight':0}, inplace=True)

In [14]:
amazon=pd.read_csv('csv_files/amazon_short.csv', dtype = {'custom_id':int})
amazon.fillna({'brand':'',
                'modelno':'',
                'title':'',
                'price':0,
                'descr':'',
                'dimensions':'',
                'shipweight':''}, inplace=True)

In [156]:
def deal_with_brand(brand):
    return brand.lower()

def deal_with_modelno(modelno):
    tmp=[]
    useless_chars=['-','/','#']
    for char in modelno:
        if char not in useless_chars:
            tmp.append(char.lower())
    return ''.join(tmp)

def deal_with_title(title):
    return title.lower()

def deal_with_descr(descr):
    return descr.lower()

def deal_with_dimensions(dimensions):
    if dimensions=='':
        return (0,0,0)
    tmp=dimensions[:-7].split(' x ')
    tmp=[float(_) for _ in tmp]
    if len(tmp)==2:
        tmp.append(0)
    return tuple(tmp)

def deal_with_shipweight(shipweight):
    if shipweight=='':
        return 0.0
    shipweight_prefix=shipweight[:-7]
    tmp=[]
    for char in shipweight_prefix:
        if char!=' ':
            tmp.append(char)
    shipweight_prefix=''.join(tmp)
    if 'pounds' in shipweight:
        return float(shipweight_prefix)
    if 'ounces' in shipweight:
        return 0.0625*float(shipweight_prefix)

In [157]:
len_walmart=len(walmart)
walmart=pd.concat([walmart,pd.DataFrame(columns=['dimensions1','dimensions2','dimensions3'])])
for i in range(len_walmart):
    walmart['brand'][i]=deal_with_brand(walmart['brand'][i])
    walmart['modelno'][i]=deal_with_modelno(walmart['modelno'][i])
    walmart['title'][i]=deal_with_title(walmart['title'][i])
    walmart['descr'][i]=deal_with_descr(walmart['descr'][i])
    dimensions=deal_with_dimensions(walmart['dimensions'][i])
    walmart['dimensions1'][i],walmart['dimensions2'][i],walmart['dimensions3'][i]=dimensions
walmart['custom_id']=walmart['custom_id'].astype('int64')
walmart.drop(columns=['dimensions'],inplace=True)
walmart.to_csv('csv_files/walmart_cleaned.csv',index=False)

/Users/xuedi/anaconda3/envs/deepbrowse/lib/python3.6/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.
/Users/xuedi/anaconda3/envs/deepbrowse/lib/python3.6/site-packages/ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """
/Users/xuedi/anaconda3/envs/deepbrowse/lib/python3.6/site-packages/ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/Users/xuedi/anaconda3/envs/deepbrowse/lib/python3.6/site-packages/ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  import sys
/Users/xuedi/anaconda3/envs/deepbrowse/lib/python3.6/site-packages/ipykernel_launcher.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if __name__ == '__main__':

In [158]:
len_amazon=len(amazon)
amazon=pd.concat([amazon,pd.DataFrame(columns=['dimensions1','dimensions2','dimensions3'])])
for i in range(len_amazon):
    amazon['brand'][i]=deal_with_brand(amazon['brand'][i])
    amazon['modelno'][i]=deal_with_modelno(amazon['modelno'][i])
    amazon['title'][i]=deal_with_title(amazon['title'][i])
    amazon['descr'][i]=deal_with_descr(amazon['descr'][i])
    dimensions=deal_with_dimensions(amazon['dimensions'][i])
    if len(dimensions)>3:
        print(i,len(dimensions),amazon['title'][i])
        continue
    amazon['dimensions1'][i],amazon['dimensions2'][i],amazon['dimensions3'][i]=dimensions
    amazon['shipweight'][i]=deal_with_shipweight(amazon['shipweight'][i])
amazon['custom_id']=amazon['custom_id'].astype('int64')
amazon.drop(columns=['dimensions'],inplace=True)
amazon.to_csv('csv_files/amazon_cleaned.csv',index=False)

/Users/xuedi/anaconda3/envs/deepbrowse/lib/python3.6/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.
/Users/xuedi/anaconda3/envs/deepbrowse/lib/python3.6/site-packages/ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """
/Users/xuedi/anaconda3/envs/deepbrowse/lib/python3.6/site-packages/ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/Users/xuedi/anaconda3/envs/deepbrowse/lib/python3.6/site-packages/ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  import sys
/Users/xuedi/anaconda3/envs/deepbrowse/lib/python3.6/site-packages/ipykernel_launcher.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if sys.path[0] == '':
/Users/xuedi/anaconda3/envs/deepbrowse/lib/python3.6/site-packages/ipykernel_launcher.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  del sys.path[0]

In [159]:
import sys
import py_entitymatching as em
import pandas as pd
import os

In [7]:
path_A='csv_files/walmart_cleaned.csv'
path_B='csv_files/amazon_cleaned.csv'

In [8]:
A=em.read_csv_metadata(path_A,key='custom_id')
B=em.read_csv_metadata(path_B,key='custom_id')
em.get_key(A), em.get_key(B)

Metadata file is not present in the given path; proceeding to read the csv file.
Metadata file is not present in the given path; proceeding to read the csv file.

('custom_id', 'custom_id')

In [9]:
A.fillna({'brand':'',
                'modelno':'',
                'title':'',
                'price':0,
                'descr':'',
                'dimensions1':0,'dimensions2':0,'dimensions3':0,
                'shipweight':0}, inplace=True)

In [10]:
B.fillna({'brand':'',
                'modelno':'',
                'title':'',
                'price':0,
                'descr':'',
                'dimensions1':0,'dimensions2':0,'dimensions3':0,
                'shipweight':''}, inplace=True)

In [11]:
print('Number of tuples in A: ' + str(len(A)))
print('Number of tuples in B: ' + str(len(B)))
print('Number of tuples in A X B (i.e the cartesian product): ' + str(len(A)*len(B)))

Number of tuples in A: 2554
Number of tuples in B: 22074
Number of tuples in A X B (i.e the cartesian product): 56376996

In [12]:
A.head()

,custom_id,brand,modelno,title,price,descr,shipweight,dimensions1,dimensions2,dimensions3
0,1,draper,121066,draper infrared remote transmitter,58.45,infrared transmitter. 3-button operation for instant access to up down and stop functions. full...,2.00,0.00,0.00,0.0
1,2,epson,elplp12,epson 1500 hours 200w uhe projector lamp elplp12,438.84,,0.95,6.75,5.75,5.5
2,3,comprehensive,bj2c7559,comprehensive two-piece 75 precision bnc jack for rg-59 set of 25,59.25,comprehensive s true 75 connectors eliminate impedance mismatching and distortion that can be ca...,0.05,0.00,0.00,0.0
3,4,d-link,dcs1100,d-link dcs-1100 network camera,99.82,surveillance network camera built-in omni-directional microphone supports 4 profiles simultane...,0.00,0.00,0.00,0.0
4,5,startech,rkpw247015,startech.com rkpw247015 24 outlet power strip,59.00,fits most 42u racks and equipment cabinets 10 ft. power cord provides plenty of reach to power ...,5.25,72.50,2.50,1.5

In [13]:
B.head()

,custom_id,brand,modelno,title,price,descr,shipweight,dimensions1,dimensions2,dimensions3
0,1,koss,152132,koss eq50 3-band stereo equalizer,12.65,the pocket-size koss 3-band equalizer delivers high-fidelity performance and output normally res...,1.0,7.6,4.8,1.4
1,2,kodak,1163641,kodak black ink cartridge 10b 1163641,10.28,kodak black ink cartridge 10b is a standard black ink cartridge,1.0,5.3,3.2,1.2
2,3,kingston,ktcd3201g,kingston 128mx64 pc2700 compaq evo d320 ktc-d320 1g,33.75,1gb - 333mhz ddr333 pc2700 - ddr sdram - 184-pin dimm,1.0,6.8,2.2,0.5
3,4,kinamax,msues2,kinamax ms-ues2 mini high precision usb 3-button 3d optical scroll wheel mouse with retractable ...,6.99,kinamax ms-ues2 mini high precision usb 3-button 3d optical scroll wheel mouse with retractable ...,1.0,4.3,2.8,1.3
4,5,kensington,k72349us,kensington k72349us wireless mouse for netbooks,24.00,wireless mouse for netbooks usbwrls,1.0,4.1,3.2,1.5

In [167]:
# Blocking

# Overlap blocking over input tables on title: the title of matched entities should have at least 2 same words
ob=em.OverlapBlocker()
C1=ob.block_tables(A,B,'title','title',word_level=True,overlap_size=2,allow_missing=True,
                 l_output_attrs=['brand','modelno','title','price','descr','shipweight','dimensions1','dimensions2','dimensions3'],
                 r_output_attrs=['brand','modelno','title','price','descr','shipweight','dimensions1','dimensions2','dimensions3'],
                 show_progress=True)
print(len(C1))

C2=ob.block_tables(A,B,'brand','brand',word_level=True,overlap_size=1,allow_missing=True,
                 l_output_attrs=['brand','modelno','title','price','descr','shipweight','dimensions1','dimensions2','dimensions3'],
                 r_output_attrs=['brand','modelno','title','price','descr','shipweight','dimensions1','dimensions2','dimensions3'],
                 show_progress=True)
print(len(C2))

C3=em.combine_blocker_outputs_via_union([C1,C2])
print(len(C3))

/Users/xuedi/anaconda3/envs/deepbrowse/lib/python3.6/site-packages/py_stringsimjoin/utils/converter.py:99: FutureWarning: The pandas.np module is deprecated and will be removed from pandas in a future version. Import numpy directly instead
  if col_type == pd.np.object:
/Users/xuedi/anaconda3/envs/deepbrowse/lib/python3.6/site-packages/py_entitymatching/blocker/overlap_blocker.py:258: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  l_df[l_dummy_overlap_attr] = l_df[l_overlap_attr]
/Users/xuedi/anaconda3/envs/deepbrowse/lib/python3.6/site-packages/py_entitymatching/blocker/overlap_blocker.py:259: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  r_df[r_dummy_overlap_attr] = r_df[r_overlap_attr]
/Users/xuedi/anaconda3/envs/deepbrowse/lib/python3.6/site-packages/py_entitymatching/blocker/overlap_blocker.py:615: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  table[overlap_attr] = values
/Users/xuedi/anaconda3/envs/deepbrowse/lib/python3.6/site-packages/py_stringsimjoin/utils/validation.py:30: FutureWarning: The pandas.np module is deprecated and will be removed from pandas in a future version. Import numpy directly instead
  if attr_type != pd.np.object:
0% [##############################] 100% | ETA: 00:00:00
Total time elapsed: 00:00:08

Finding pairs with missing value...
1138953

/Users/xuedi/anaconda3/envs/deepbrowse/lib/python3.6/site-packages/py_stringsimjoin/utils/converter.py:99: FutureWarning: The pandas.np module is deprecated and will be removed from pandas in a future version. Import numpy directly instead
  if col_type == pd.np.object:
/Users/xuedi/anaconda3/envs/deepbrowse/lib/python3.6/site-packages/py_entitymatching/blocker/overlap_blocker.py:258: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  l_df[l_dummy_overlap_attr] = l_df[l_overlap_attr]
/Users/xuedi/anaconda3/envs/deepbrowse/lib/python3.6/site-packages/py_entitymatching/blocker/overlap_blocker.py:259: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  r_df[r_dummy_overlap_attr] = r_df[r_overlap_attr]
/Users/xuedi/anaconda3/envs/deepbrowse/lib/python3.6/site-packages/py_entitymatching/blocker/overlap_blocker.py:615: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  table[overlap_attr] = values
/Users/xuedi/anaconda3/envs/deepbrowse/lib/python3.6/site-packages/py_stringsimjoin/utils/validation.py:30: FutureWarning: The pandas.np module is deprecated and will be removed from pandas in a future version. Import numpy directly instead
  if attr_type != pd.np.object:
0% [##############################] 100% | ETA: 00:00:00
Total time elapsed: 00:00:01

Finding pairs with missing value...
280700
1312072

In [168]:
C3.columns

Index(['_id', 'ltable_custom_id', 'rtable_custom_id', 'ltable_brand',
       'ltable_modelno', 'ltable_title', 'ltable_price', 'ltable_descr',
       'ltable_shipweight', 'ltable_dimensions1', 'ltable_dimensions2',
       'ltable_dimensions3', 'rtable_brand', 'rtable_modelno', 'rtable_title',
       'rtable_price', 'rtable_descr', 'rtable_shipweight',
       'rtable_dimensions1', 'rtable_dimensions2', 'rtable_dimensions3'],
      dtype='object')

In [169]:
# Check whether the matched entities are all in the candset

# Construct the (ltable_custom_id,rtable_custom_id)->index atching in candset
candsetId_to_index={}
for index, row in C3.iterrows():
    ltable_id,rtable_id=row['ltable_custom_id'],row['rtable_custom_id']
    if ltable_id not in candsetId_to_index:
        candsetId_to_index[ltable_id]={}
    candsetId_to_index[ltable_id][rtable_id]=index
    
    
# Traverse the matched entities in matching groundtruth,
# and checks whether the matched entities are all in the candset
error_id=1
match=pd.read_csv('csv_files/matches_walmart_amazon.csv')
length=len(match)
for i in range(length):
    idWalmart=match['id1'][i]
    idAmazon=match['id2'][i]
    if idWalmart not in candsetId_to_index:
        print('Error {}: matched entities ({},{}) not in candset!'.format(error_id,idWalmart,idAmazon))
        error_id+=1
    else:
        if idAmazon not in candsetId_to_index[idWalmart]:
            print('Error {}: matched entities ({},{}) not in candset!'.format(error_id,idWalmart,idAmazon))
            error_id+=1

In [170]:
atypes1 = em.get_attr_types(A)
atypes2 = em.get_attr_types(B)
atypes1['title']='str_bt_1w_5w'
atypes2['title']='str_bt_1w_5w'
block_c = em.get_attr_corres(A, B)
tok = em.get_tokenizers_for_matching()
sim = em.get_sim_funs_for_matching()
feature_table = em.get_features(A, B, atypes1, atypes2, block_c, tok, sim)
feature_table

/Users/xuedi/anaconda3/envs/deepbrowse/lib/python3.6/site-packages/py_entitymatching/feature/attributeutils.py:191: FutureWarning: The pandas.np module is deprecated and will be removed from pandas in a future version. Import numpy directly instead
  if returned_type == bool or returned_type == pd.np.bool_:

,feature_name,left_attribute,right_attribute,left_attr_tokenizer,right_attr_tokenizer,simfunction,function,function_source,is_auto_generated
0,custom_id_custom_id_exm,custom_id,custom_id,None,None,exact_match,<function custom_id_custom_id_exm at 0x7fb542631730>,from py_entitymatching.feature.simfunctions import *\nfrom py_entitymatching.feature.tokenizers ...,True
1,custom_id_custom_id_anm,custom_id,custom_id,None,None,abs_norm,<function custom_id_custom_id_anm at 0x7fb6a5b158c8>,from py_entitymatching.feature.simfunctions import *\nfrom py_entitymatching.feature.tokenizers ...,True
2,custom_id_custom_id_lev_dist,custom_id,custom_id,None,None,lev_dist,<function custom_id_custom_id_lev_dist at 0x7fb6a5b15a60>,from py_entitymatching.feature.simfunctions import *\nfrom py_entitymatching.feature.tokenizers ...,True
3,custom_id_custom_id_lev_sim,custom_id,custom_id,None,None,lev_sim,<function custom_id_custom_id_lev_sim at 0x7fb6a5b159d8>,from py_entitymatching.feature.simfunctions import *\nfrom py_entitymatching.feature.tokenizers ...,True
4,brand_brand_jac_qgm_3_qgm_3,brand,brand,qgm_3,qgm_3,jaccard,<function brand_brand_jac_qgm_3_qgm_3 at 0x7fb6a5b157b8>,from py_entitymatching.feature.simfunctions import *\nfrom py_entitymatching.feature.tokenizers ...,True
5,brand_brand_cos_dlm_dc0_dlm_dc0,brand,brand,dlm_dc0,dlm_dc0,cosine,<function brand_brand_cos_dlm_dc0_dlm_dc0 at 0x7fb6a5b15840>,from py_entitymatching.feature.simfunctions import *\nfrom py_entitymatching.feature.tokenizers ...,True
6,brand_brand_jac_dlm_dc0_dlm_dc0,brand,brand,dlm_dc0,dlm_dc0,jaccard,<function brand_brand_jac_dlm_dc0_dlm_dc0 at 0x7fb6a5b15950>,from py_entitymatching.feature.simfunctions import *\nfrom py_entitymatching.feature.tokenizers ...,True
7,brand_brand_mel,brand,brand,None,None,monge_elkan,<function brand_brand_mel at 0x7fb5517ec9d8>,from py_entitymatching.feature.simfunctions import *\nfrom py_entitymatching.feature.tokenizers ...,True
8,brand_brand_lev_dist,brand,brand,None,None,lev_dist,<function brand_brand_lev_dist at 0x7fb5517ecbf8>,from py_entitymatching.feature.simfunctions import *\nfrom py_entitymatching.feature.tokenizers ...,True
9,brand_brand_lev_sim,brand,brand,None,None,lev_sim,<function brand_brand_lev_sim at 0x7fb5517eca60>,from py_entitymatching.feature.simfunctions import *\nfrom py_entitymatching.feature.tokenizers ...,True
10,brand_brand_nmw,brand,brand,None,None,needleman_wunsch,<function brand_brand_nmw at 0x7fb5517ec840>,from py_entitymatching.feature.simfunctions import *\nfrom py_entitymatching.feature.tokenizers ...,True
11,brand_brand_sw,brand,brand,None,None,smith_waterman,<function brand_brand_sw at 0x7fb5517ec7b8>,from py_entitymatching.feature.simfunctions import *\nfrom py_entitymatching.feature.tokenizers ...,True
12,modelno_modelno_jac_qgm_3_qgm_3,modelno,modelno,qgm_3,qgm_3,jaccard,<function modelno_modelno_jac_qgm_3_qgm_3 at 0x7fb5517ecc80>,from py_entitymatching.feature.simfunctions import *\nfrom py_entitymatching.feature.tokenizers ...,True
13,modelno_modelno_cos_dlm_dc0_dlm_dc0,modelno,modelno,dlm_dc0,dlm_dc0,cosine,<function modelno_modelno_cos_dlm_dc0_dlm_dc0 at 0x7fb5517ecd08>,from py_entitymatching.feature.simfunctions import *\nfrom py_entitymatching.feature.tokenizers ...,True
14,modelno_modelno_jac_dlm_dc0_dlm_dc0,modelno,modelno,dlm_dc0,dlm_dc0,jaccard,<function modelno_modelno_jac_dlm_dc0_dlm_dc0 at 0x7fb5517ece18>,from py_entitymatching.feature.simfunctions import *\nfrom py_entitymatching.feature.tokenizers ...,True
15,modelno_modelno_mel,modelno,modelno,None,None,monge_elkan,<function modelno_modelno_mel at 0x7fb5517ecea0>,from py_entitymatching.feature.simfunctions import *\nfrom py_entitymatching.feature.tokenizers ...,True
16,modelno_modelno_lev_dist,modelno,modelno,None,None,lev_dist,<function modelno_modelno_lev_dist at 0x7fb5517ecd90>,from py_entitymatching.feature.simfunctions import *\nfrom py_entitymatching.feature.tokenizers ...,True
17,modelno_modelno_lev_sim,modelno,modelno,None,None,lev_sim,<function modelno_modelno_lev_sim at 0x7fb5517ec8c8>,from py_entitymatching.feature.simfunctions import *\nfrom py_entitymatching.feature.tokenizers ...,True
18,modelno_modelno_nmw,modelno,modelno,None,None,needleman_wunsch,<function modelno_modelno_nmw at 0x7fb5517ecae8>,from py_entitymatching.feature.simfunctions import *\nfrom py_entitymatching.feature.tokenizers ...,True
19,modelno_modelno_sw,modelno,modelno,None,None,smith_waterman,<function modelno_modelno_sw at 0x7fb466f7d048>,from py_entitymatching.feature.simfunctions import *\nfrom py_entitymatching.feature.tokenizers ...,True
20,title_title_jac_qgm_3_qgm_3,title,title,qgm_3,qgm_3,jaccard,<function title_title_jac_qgm_3_qgm_3 at 0x7fb466f7d0d0>,from py_entitymatching.feature.simfunctions import *\nfrom py_entitymatching.feature.tokenizers ...,True
21,title_title_cos_dlm_dc0_dlm_dc0,title,title,dlm_dc0,dlm_dc0,cosine,<function title_title_cos_dlm_dc0_dlm_dc0 at 0x7fb466f7d158>,from py_entitymatching.feature.simfunctions import *\nfrom py_entitymatching.feature.tokenizers ...,True
22,title_title_jac_dlm_dc0_dlm_dc0,title,title,dlm_dc0,dlm_dc0,jaccard,<function title_title_jac_dlm_dc0_dlm_dc0 at 0x7fb466f7d1e0>,from py_entitymatching.feature.simfunctions import *\nfrom py_entitymatching.feature.tokenizers ...,True
23,title_title_mel,title,title,None,None,monge_elkan,<function title_title_mel at 0x7fb466f7d268>,from py_entitymatching.feature.simfunctions import *\nfrom py_entitymatching.feature.tokenizers ...,True
24,title_title_lev_dist,title,title,None,None,lev_dist,<function title_title_lev_dist at 0x7fb466f7d2f0>,from py_entitymatching.feature.simfunctions import *\nfrom py_entitymatching.feature.tokenizers ...,True
25,title_title_lev_sim,title,title,None,None,lev_sim,<function title_title_lev_sim at 0x7fb466f7d378>,from py_entitymatching.feature.simfunctions import *\nfrom py_entitymatching.feature.tokenizers ...,True
26,title_title_nmw,title,title,None,None,needleman_wunsch,<function title_title_nmw at 0x7fb466f7d400>,from py_entitymatching.feature.simfunctions import *\nfrom py_entitymatching.feature.tokenizers ...,True
27,title_title_sw,title,title,None,None,smith_waterman,<function title_title_sw at 0x7fb466f7d488>,from py_entitymatching.feature.simfunctions import *\nfrom py_entitymatching.feature.tokenizers ...,True
28,price_price_exm,price,price,None,None,exact_match,<function price_price_exm at 0x7fb466f7d510>,from py_entitymatching.feature.simfunctions import *\nfrom py_entitymatching.feature.tokenizers ...,True
29,price_price_anm,price,price,None,None,abs_norm,<function price_price_anm at 0x7fb466f7d598>,from py_entitymatching.feature.simfunctions import *\nfrom py_entitymatching.feature.tokenizers ...,True
30,price_price_lev_dist,price,price,None,None,lev_dist,<function price_price_lev_dist at 0x7fb466f7d620>,from py_entitymatching.feature.simfunctions import *\nfrom py_entitymatching.feature.tokenizers ...,True
31,price_price_lev_sim,price,price,None,None,lev_sim,<function price_price_lev_sim at 0x7fb466f7d6a8>,from py_entitymatching.feature.simfunctions import *\nfrom py_entitymatching.feature.tokenizers ...,True
32,descr_descr_jac_qgm_3_qgm_3,descr,descr,qgm_3,qgm_3,jaccard,<function descr_descr_jac_qgm_3_qgm_3 at 0x7fb466f7d730>,from py_entitymatching.feature.simfunctions import *\nfrom py_entitymatching.feature.tokenizers ...,True
33,descr_descr_cos_dlm_dc0_dlm_dc0,descr,descr,dlm_dc0,dlm_dc0,cosine,<function descr_descr_cos_dlm_dc0_dlm_dc0 at 0x7fb466f7d7b8>,from py_entitymatching.feature.simfunctions import *\nfrom py_entitymatching.feature.tokenizers ...,True
34,shipweight_shipweight_exm,shipweight,shipweight,None,None,exact_match,<function shipweight_shipweight_exm at 0x7fb466f7d840>,from py_entitymatching.feature.simfunctions import *\nfrom py_entitymatching.feature.tokenizers ...,True
35,shipweight_shipweight_anm,shipweight,shipweight,None,None,abs_norm,<function shipweight_shipweight_anm at 0x7fb466f7d8c8>,from py_entitymatching.feature.simfunctions import *\nfrom py_entitymatching.feature.tokenizers ...,True
36,shipweight_shipweight_lev_dist,shipweight,shipweight,None,None,lev_dist,<function shipweight_shipweight_lev_dist at 0x7fb466f7d950>,from py_entitymatching.feature.simfunctions import *\nfrom py_entitymatching.feature.tokenizers ...,True
37,shipweight_shipweight_lev_sim,shipweight,shipweight,None,None,lev_sim,<function shipweight_shipweight_lev_sim at 0x7fb466f7d9d8>,from py_entitymatching.feature.simfunctions import *\nfrom py_entitymatching.feature.tokenizers ...,True
38,dimensions1_dimensions1_exm,dimensions1,dimensions1,None,None,exact_match,<function dimensions1_dimensions1_exm at 0x7fb466f7da60>,from py_entitymatching.feature.simfunctions import *\nfrom py_entitymatching.feature.tokenizers ...,True
39,dimensions1_dimensions1_anm,dimensions1,dimensions1,None,None,abs_norm,<function dimensions1_dimensions1_anm at 0x7fb466f7dae8>,from py_entitymatching.feature.simfunctions import *\nfrom py_entitymatching.feature.tokenizers ...,True
40,dimensions1_dimensions1_lev_dist,dimensions1,dimensions1,None,None,lev_dist,<function dimensions1_dimensions1_lev_dist at 0x7fb466f7db70>,from py_entitymatching.feature.simfunctions import *\nfrom py_entitymatching.feature.tokenizers ...,True
41,dimensions1_dimensions1_lev_sim,dimensions1,dimensions1,None,None,lev_sim,<function dimensions1_dimensions1_lev_sim at 0x7fb466f7dbf8>,from py_entitymatching.feature.simfunctions import *\nfrom py_entitymatching.feature.tokenizers ...,True
42,dimensions2_dimensions2_exm,dimensions2,dimensions2,None,None,exact_match,<function dimensions2_dimensions2_exm at 0x7fb466f7dc80>,from py_entitymatching.feature.simfunctions import *\nfrom py_entitymatching.feature.tokenizers ...,True
43,dimensions2_dimensions2_anm,dimensions2,dimensions2,None,None,abs_norm,<function dimensions2_dimensions2_anm at 0x7fb466f7dd08>,from py_entitymatching.feature.simfunctions import *\nfrom py_entitymatching.feature.tokenizers ...,True
44,dimensions2_dimensions2_lev_dist,dimensions2,dimensions2,None,None,lev_dist,<function dimensions2_dimensions2_lev_dist at 0x7fb466f7dd90>,from py_entitymatching.feature.simfunctions import *\nfrom py_entitymatching.feature.tokenizers ...,True
45,dimensions2_dimensions2_lev_sim,dimensions2,dimensions2,None,None,lev_sim,<function dimensions2_dimensions2_lev_sim at 0x7fb466f7de18>,from py_entitymatching.feature.simfunctions import *\nfrom py_entitymatching.feature.tokenizers ...,True
46,dimensions3_dimensions3_exm,dimensions3,dimensions3,None,None,exact_match,<function dimensions3_dimensions3_exm at 0x7fb466f7dea0>,from py_entitymatching.feature.simfunctions import *\nfrom py_entitymatching.feature.tokenizers ...,True
47,dimensions3_dimensions3_anm,dimensions3,dimensions3,None,None,abs_norm,<function dimensions3_dimensions3_anm at 0x7fb466f7df28>,from py_entitymatching.feature.simfunctions import *\nfrom py_entitymatching.feature.tokenizers ...,True
48,dimensions3_dimensions3_lev_dist,dimensions3,dimensions3,None,None,lev_dist,<function dimensions3_dimensions3_lev_dist at 0x7fb466f7f048>,from py_entitymatching.feature.simfunctions import *\nfrom py_entitymatching.feature.tokenizers ...,True
49,dimensions3_dimensions3_lev_sim,dimensions3,dimensions3,None,None,lev_sim,<function dimensions3_dimensions3_lev_sim at 0x7fb466f7f0d0>,from py_entitymatching.feature.simfunctions import *\nfrom py_entitymatching.feature.tokenizers ...,True

In [171]:
feature_table.to_csv('csv_files/feature_table.csv')

In [172]:
walmart_match_dic={}
amazon_match_dic={}
match=pd.read_csv('csv_files/matches_walmart_amazon.csv')
length=len(match)
for i in range(length):
    idWalmart=match['id1'][i]
    idAmazon=match['id2'][i]
    if idWalmart in walmart_match_dic:
        walmart_match_dic[idWalmart].append(idAmazon)
    else:
        walmart_match_dic[idWalmart]=[idAmazon]
    if idAmazon in amazon_match_dic:
        amazon_match_dic[idAmazon].append(idWalmart)
    else:
        amazon_match_dic[idAmazon]=[idWalmart]
for idWalmart in walmart_match_dic:
    if len(walmart_match_dic[idWalmart])>1:
        print(idWalmart,walmart_match_dic[idWalmart])
for idAmazon in amazon_match_dic:
    if len(amazon_match_dic[idAmazon])>1:
        print(idAmazon,amazon_match_dic[idAmazon])

len(walmart_match_dic),len(amazon_match_dic)

1234 [12408, 18429]
1719 [12857, 8846]
2156 [4510, 17865, 4319]
1973 [3591, 3594]
524 [7631, 3627]
1559 [4509, 12853]
1467 [13593, 15576, 11642]
1844 [9692, 4901]
1154 [13246, 9238]
1642 [11045, 15010]
1440 [19655, 1637]
247 [19032, 13590]
89 [3270, 18981]
1316 [7784, 15123, 21113]
1194 [4494, 5593]
331 [16953, 1600]
640 [7372, 10129]
1008 [11117, 18143]
1146 [4788, 2868]
2409 [6809, 5519]
2197 [19485, 17367]
1937 [18141, 11296]
2089 [22026, 17264]
195 [20940, 6877]
2015 [11741, 9457]
1698 [16579, 21668]
1695 [20398, 11027, 3794]
726 [16801, 16278]
397 [7150, 17849, 7145]
1209 [18171, 3255, 16936]
1529 [16917, 812]
2406 [18333, 8669]
1281 [7638, 17950]
863 [5783, 11819]
560 [20714, 21311]
322 [20698, 4630]
2365 [16367, 17916]
551 [19540, 2556]
109 [12442, 21710]
2005 [19521, 1748]
482 [14854, 987]
1523 [21030, 1026]
16 [4283, 17365, 17811]
1039 [5011, 19036]
1110 [6058, 8092]
1300 [14224, 15463]
66 [7157, 11130]
192 [1244, 11198]
70 [14642, 21810]
87 [7611, 11618]
262 [5193, 3239]
2200 [18139, 20396]
2361 [7250, 17906]
2191 [2311, 21662]
2267 [1617, 13319]
2217 [17495, 20676]
2134 [8991, 10435]
1401 [14944, 18728]
811 [1481, 11429]
416 [17244, 20386]
1094 [5463, 16870]
2022 [17375, 17452]
1981 [4279, 1503]
590 [16954, 15496]
1210 [14110, 9718]
2027 [3204, 18649]
149 [16351, 18937, 16399]
700 [4284, 3857]
1415 [2486, 11940]
1350 [12192, 4660]
2345 [6971, 14945, 4985]
470 [19258, 2721]
706 [16537, 12896]
529 [21348, 77]
1603 [19808, 10609]
833 [4598, 19557]
2094 [16312, 11401]
121 [14796, 13523]
1933 [9096, 9017]
2038 [21544, 8520]
2469 [10814, 16833]
1910 [11285, 20494]
414 [285, 1678]
1474 [3251, 3249]
1969 [10525, 21512]
303 [16808, 16642]
785 [12734, 21197]
531 [18532, 6616]
160 [5665, 9710]
578 [19368, 21737]
2218 [19468, 18301]
1989 [2477, 9475]
20 [17430, 13058]
1247 [17192, 21595]
223 [17535, 1355]
903 [6662, 18251]
724 [1690, 9676]
1592 [3206, 17448]
361 [19151, 11567]
2463 [8176, 14118]
2137 [19007, 4706]
1814 [1608, 3254]
476 [20393, 12747, 782]
1476 [8651, 12655]
899 [7384, 11344, 15336]
1687 [20039, 17666]
708 [11830, 8043]
2168 [14881, 17734]
653 [7446, 6709]
1762 [4577, 12648]
1201 [160, 19355]
2019 [11228, 5208]
546 [7625, 7623]
849 [3154, 603]
1759 [13846, 9790]
1842 [2327, 18624]
1833 [433, 13397]
2195 [18385, 5102]
694 [2612, 105]
539 [17175, 10462]
466 [7305, 15279]
6 [10423, 20933]
2194 [5683, 9731]
2380 [265, 10268]
129 [10641, 2702]
576 [1129, 5076]
601 [12882, 4692]
454 [10900, 4893]
57 [21965, 9165]
1346 [14258, 20146]
2327 [19269, 1682]
1777 [15490, 16438, 13180]
802 [8932, 13030]
164 [9825, 124]
2143 [5921, 13935]
1988 [10906, 16253]
363 [3236, 16308]
2166 [21077, 18478]
4785 [2344, 2150]
8619 [1335, 2366]
19120 [2483, 2550]
3068 [35, 2057]
4227 [876, 1691]
14110 [1210, 1122]
3627 [599, 524]
8520 [325, 2038]

(1004, 1146)

In [173]:
# Get gold_groundtruth_blocking
gt_blocking=open('csv_files/gold_groundtruth_blocking.csv','w')
gt_blocking.write('"_id","idWalmart","idAmazon","gold"\n')
_id=0
for index, row in C3.iterrows():
    ltable_id,rtable_id=row['ltable_custom_id'],row['rtable_custom_id']
    if ltable_id in walmart_match_dic:
        if rtable_id in walmart_match_dic[ltable_id]:
            gt_blocking.write(str(_id)+','+str(ltable_id)+','+str(rtable_id)+',1\n')
            _id+=1
        else:
            gt_blocking.write(str(_id)+','+str(ltable_id)+','+str(rtable_id)+',0\n')
            _id+=1
    else:
        gt_blocking.write(str(_id)+','+str(ltable_id)+','+str(rtable_id)+',0\n')
        _id+=1
gt_blocking.close()

In [174]:
path_G='csv_files/gold_groundtruth_blocking.csv'
G=em.read_csv_metadata(path_G, 
                         key='_id',
                         ltable=A, rtable=B, 
                         fk_ltable="idWalmart", fk_rtable="idAmazon")
len(G)

Metadata file is not present in the given path; proceeding to read the csv file.

1312072

In [175]:
# feature_table=feature_table.iloc[[4,12,20,32]]
feature_table=feature_table.iloc[[4,12,20]]
feature_table.reset_index(drop=True)
feature_table

,feature_name,left_attribute,right_attribute,left_attr_tokenizer,right_attr_tokenizer,simfunction,function,function_source,is_auto_generated
4,brand_brand_jac_qgm_3_qgm_3,brand,brand,qgm_3,qgm_3,jaccard,<function brand_brand_jac_qgm_3_qgm_3 at 0x7fb6a5b157b8>,from py_entitymatching.feature.simfunctions import *\nfrom py_entitymatching.feature.tokenizers ...,True
12,modelno_modelno_jac_qgm_3_qgm_3,modelno,modelno,qgm_3,qgm_3,jaccard,<function modelno_modelno_jac_qgm_3_qgm_3 at 0x7fb5517ecc80>,from py_entitymatching.feature.simfunctions import *\nfrom py_entitymatching.feature.tokenizers ...,True
20,title_title_jac_qgm_3_qgm_3,title,title,qgm_3,qgm_3,jaccard,<function title_title_jac_qgm_3_qgm_3 at 0x7fb466f7d0d0>,from py_entitymatching.feature.simfunctions import *\nfrom py_entitymatching.feature.tokenizers ...,True

In [176]:
# Convert the labeled data to feature vectors using the feature table
em.get_property(G,'key')

G = em.extract_feature_vecs(G, 
                            feature_table=feature_table, 
#                             attrs_before = attrs_from_table,
                            attrs_after='gold',
                            show_progress=True)

/Users/xuedi/anaconda3/envs/deepbrowse/lib/python3.6/site-packages/py_entitymatching/feature/extractfeatures.py:158: FutureWarning: The pandas.np module is deprecated and will be removed from pandas in a future version. Import numpy directly instead
  c_splits = pd.np.array_split(candset, n_procs)
0% [##############################] 100% | ETA: 00:00:00
Total time elapsed: 00:09:37

In [177]:
G.head()

,_id,idWalmart,idAmazon,brand_brand_jac_qgm_3_qgm_3,modelno_modelno_jac_qgm_3_qgm_3,title_title_jac_qgm_3_qgm_3,gold
0,0,1,976,0.0625,0.0,0.162500,0
1,1,1,1113,1.0000,0.0,0.029851,0
2,2,1,2990,0.0000,0.0,0.194030,0
3,3,1,3330,0.0000,0.0,0.134752,0
4,4,1,4408,0.0625,0.0,0.250000,0

In [178]:
brand_walmart=[]
brand_amazon=[]
modelno_walmart=[]
modelno_amazon=[]

for index, row in G.iterrows():
    idWalmart=row['idWalmart']
    idAmazon=row['idAmazon']
    
    if A['brand'][idWalmart-1]:
        brand_walmart.append(1)
    else:
        brand_walmart.append(0)
        
    if A['modelno'][idWalmart-1]:
        modelno_walmart.append(1)
    else:
        modelno_walmart.append(0)
        
    if B['brand'][idAmazon-1]:
        brand_amazon.append(1)
    else:
        brand_amazon.append(0)
        
    if B['modelno'][idAmazon-1]:
        modelno_amazon.append(1)
    else:
        modelno_amazon.append(0)
        
my_G=pd.DataFrame({'brand_walmart':brand_walmart,
               'brand_amazon':brand_amazon,
               'modelno_walmart':modelno_walmart,
               'modelno_amazon':modelno_amazon})
G=pd.concat([G,my_G],axis=1)

In [179]:
G.head()

,_id,idWalmart,idAmazon,brand_brand_jac_qgm_3_qgm_3,modelno_modelno_jac_qgm_3_qgm_3,title_title_jac_qgm_3_qgm_3,gold,brand_walmart,brand_amazon,modelno_walmart,modelno_amazon
0,0,1,976,0.0625,0.0,0.162500,0,1,1,1,1
1,1,1,1113,1.0000,0.0,0.029851,0,1,1,1,1
2,2,1,2990,0.0000,0.0,0.194030,0,1,1,1,1
3,3,1,3330,0.0000,0.0,0.134752,0,1,1,1,1
4,4,1,4408,0.0625,0.0,0.250000,0,1,1,1,0

In [182]:
columns=['_id',
         'idWalmart',
         'idAmazon',
         'brand_brand_jac_qgm_3_qgm_3',
         'modelno_modelno_jac_qgm_3_qgm_3',
         'title_title_jac_qgm_3_qgm_3',
         'brand_walmart',
         'brand_amazon',
         'modelno_walmart',
         'modelno_amazon',
         'gold']
G=G[columns]

In [183]:
G.head()

,_id,idWalmart,idAmazon,brand_brand_jac_qgm_3_qgm_3,modelno_modelno_jac_qgm_3_qgm_3,title_title_jac_qgm_3_qgm_3,brand_walmart,brand_amazon,modelno_walmart,modelno_amazon,gold
0,0,1,976,0.0625,0.0,0.162500,1,1,1,1,0
1,1,1,1113,1.0000,0.0,0.029851,1,1,1,1,0
2,2,1,2990,0.0000,0.0,0.194030,1,1,1,1,0
3,3,1,3330,0.0000,0.0,0.134752,1,1,1,1,0
4,4,1,4408,0.0625,0.0,0.250000,1,1,1,0,0

In [184]:
G.to_csv('csv_files/hhh_blocking.csv',index=False)

In [61]:
def jac_qgm_3_qgm_3(seq1, seq2):
    qgm1 = []
    qgm2 = []
    seq1 = '##' + seq1 + '$$'
    seq2 = '##' + seq2 + '$$'
    for i in range(len(seq1) - 2):
        qgm1.append(seq1[i:i + 3])
    for i in range(len(seq2) - 2):
        qgm2.append(seq2[i:i + 3])
    qgm1 = set(qgm1)
    qgm2 = set(qgm2)
    return len(qgm1 & qgm2) / len(qgm1 | qgm2)

In [63]:
match=pd.read_csv('csv_files/matches_walmart_amazon.csv')
length=len(match)

columns=['brand','modelno','title','price','shipweight']
for col in columns:
    match_info=open('csv_files/match_info/{}.csv'.format(col),'w')
    for i in range(length):
        idWalmart=match['id1'][i]
        idAmazon=match['id2'][i]
        seq1=A.iloc[idWalmart-1][col]
        seq2=B.iloc[idAmazon-1][col]
        if col in ['brand','modelno','title']:
            sim=jac_qgm_3_qgm_3(seq1,seq2)
            match_info.write('{}***{}***{}\n'.format(seq1,seq2,sim))
        else:
            match_info.write('{}***{}\n'.format(seq1,seq2))
    match_info.close()
    
match_info=open('csv_files/match_info/descr.csv','w')
for i in range(length):
    idWalmart=match['id1'][i]
    idAmazon=match['id2'][i]
    seq1=A.iloc[idWalmart-1]['descr']
    seq2=B.iloc[idAmazon-1]['descr']
    match_info.write('*'+seq1+'\n')
    match_info.write('**'+seq2+'\n')
    sim=jac_qgm_3_qgm_3(seq1,seq2)
    match_info.write(str(sim)+'\n\n')
match_info.close()

columns=['dimensions1','dimensions2','dimensions2']
match_info=open('csv_files/match_info/dimensions.csv','w')
for i in range(length):
    idWalmart=match['id1'][i]
    idAmazon=match['id2'][i]
    for col in columns:
        match_info.write(str(A.iloc[idWalmart-1][col])+' ')
    match_info.write('*** ')
    for col in columns:
        match_info.write(str(B.iloc[idAmazon-1][col])+' ')
    match_info.write('\n')
match_info.close()

In [14]:
hhh=pd.read_csv('csv_files/hhh_blocking.csv')
print(len(hhh))
hhh.head()

1312072

,_id,idWalmart,idAmazon,brand_brand_jac_qgm_3_qgm_3,modelno_modelno_jac_qgm_3_qgm_3,title_title_jac_qgm_3_qgm_3,brand_walmart,brand_amazon,modelno_walmart,modelno_amazon,gold
0,0,1,976,0.0625,0.0,0.162500,1,1,1,1,0
1,1,1,1113,1.0000,0.0,0.029851,1,1,1,1,0
2,2,1,2990,0.0000,0.0,0.194030,1,1,1,1,0
3,3,1,3330,0.0000,0.0,0.134752,1,1,1,1,0
4,4,1,4408,0.0625,0.0,0.250000,1,1,1,0,0

In [15]:
m_data=hhh[hhh.gold==1]
u_data=hhh[hhh.gold==0]

In [16]:
m_data.head()

,_id,idWalmart,idAmazon,brand_brand_jac_qgm_3_qgm_3,modelno_modelno_jac_qgm_3_qgm_3,title_title_jac_qgm_3_qgm_3,brand_walmart,brand_amazon,modelno_walmart,modelno_amazon,gold
556,556,4,4379,1.000000,1.0,0.337209,1,1,1,1,1
926,926,6,10423,1.000000,0.0,0.297872,1,1,1,0,1
995,995,6,20933,0.285714,1.0,0.574468,1,1,1,1,1
1482,1482,7,9016,1.000000,1.0,0.524590,1,1,1,1,1
2269,2269,8,1304,1.000000,1.0,0.492958,1,1,1,1,1

In [5]:
import numpy as np
import pandas as pd
import pickle

In [226]:
# Explore walmart_cleaned.csv and amazon_cleaned.csv
print('A_size:',len(A),'B_size:',len(B))

unique_A_brand=list(np.unique(A['brand']))
unique_A_modelno=list(np.unique(A['modelno']))
f=open('variables/unique_A_brand.list','wb')
pickle.dump(unique_A_brand,f)
f.close()
f=open('variables/unique_A_modelno.list','wb')
pickle.dump(unique_A_modelno,f)
f.close()
print('len_unique_A_brand:',len(np.unique(A['brand'])), 'len_unique_A_modelno:',len(np.unique(A['modelno'])), 'len_unique_A_title:',len(np.unique(A['title'])))
unique_B_brand=list(np.unique(B['brand']))
unique_B_modelno=list(np.unique(B['modelno']))
f=open('variables/unique_B_brand.list','wb')
pickle.dump(unique_B_brand,f)
f.close()
f=open('variables/unique_B_modelno.list','wb')
pickle.dump(unique_B_modelno,f)
f.close()
print('len_unique_B_brand:',len(np.unique(B['brand'])), 'len_unique_B_modelno:',len(np.unique(B['modelno'])), 'len_unique_B_title:',len(np.unique(B['title'])),'\n')

min_A_price=max_A_price=max(A['price'])
for price in A['price']:
    if price!=0 and price<min_A_price:
        min_A_price=price
print('min_A_price:',min_A_price,'max_A_price:',max_A_price)
min_B_price=max_B_price=max(B['price'])
for price in B['price']:
    if price!=0 and price<min_B_price:
        min_B_price=price
print('min_B_price:',min_B_price,'max_B_price:',max_B_price,'\n')

min_A_shipweight=max_A_shipweight=max(A['shipweight'])
for shipweight in A['shipweight']:
    if shipweight!=0 and shipweight<min_A_shipweight:
        min_A_shipweight=shipweight
print('min_A_shipweight:',min_A_shipweight,'max_A_shipweight:',max_A_shipweight)
min_B_shipweight=max_B_shipweight=max(B['shipweight'])
for shipweight in B['shipweight']:
    if shipweight!=0 and shipweight<min_B_shipweight:
        min_B_shipweight=shipweight
print('min_B_shipweight:',min_B_shipweight,'max_B_shipweight:',max_B_shipweight,'\n')

min_A_dimensions1=max_A_dimensions1=max(A['dimensions1'])
for dimensions1 in A['dimensions1']:
    if dimensions1!=0 and dimensions1<min_A_dimensions1:
        min_A_dimensions1=dimensions1
print('min_A_dimensions1:',min_A_dimensions1,'max_A_dimensions1:',max_A_dimensions1)
min_B_dimensions1=max_B_dimensions1=max(B['dimensions1'])
for dimensions1 in B['dimensions1']:
    if dimensions1!=0 and dimensions1<min_B_dimensions1:
        min_B_dimensions1=dimensions1
print('min_B_dimensions1:',min_B_dimensions1,'max_B_dimensions1:',max_B_dimensions1,'\n')

min_A_dimensions2=max_A_dimensions2=max(A['dimensions2'])
for dimensions2 in A['dimensions2']:
    if dimensions2!=0 and dimensions2<min_A_dimensions2:
        min_A_dimensions2=dimensions2
print('min_A_dimensions2:',min_A_dimensions2,'max_A_dimensions2:',max_A_dimensions2)
min_B_dimensions2=max_B_dimensions2=max(B['dimensions2'])
for dimensions2 in B['dimensions2']:
    if dimensions2!=0 and dimensions2<min_B_dimensions2:
        min_B_dimensions2=dimensions2
print('min_B_dimensions2:',min_B_dimensions2,'max_B_dimensions2:',max_B_dimensions2,'\n')

min_A_dimensions3=max_A_dimensions3=max(A['dimensions3'])
for dimensions3 in A['dimensions3']:
    if dimensions3!=0 and dimensions3<min_A_dimensions3:
        min_A_dimensions3=dimensions3
print('min_A_dimensions3:',min_A_dimensions3,'max_A_dimensions3:',max_A_dimensions3)
min_B_dimensions3=max_B_dimensions3=max(B['dimensions3'])
for dimensions3 in B['dimensions3']:
    if dimensions3!=0 and dimensions3<min_B_dimensions3:
        min_B_dimensions3=dimensions3
print('min_B_dimensions3:',min_B_dimensions3,'max_B_dimensions3:',max_B_dimensions3)

A_size: 2554 B_size: 22074
len_unique_A_brand: 464 len_unique_A_modelno: 2389 len_unique_A_title: 2539
len_unique_B_brand: 1908 len_unique_B_modelno: 15505 len_unique_B_title: 21894

min_A_price: 1.98 max_A_price: 70416.5
min_B_price: 0.01 max_B_price: 15985.81

min_A_shipweight: 0.01 max_A_shipweight: 1375.0
min_B_shipweight: 0.0125 max_B_shipweight: 1773.0

min_A_dimensions1: 0.2 max_A_dimensions1: 801.0
min_B_dimensions1: 0.1 max_B_dimensions1: 720.0

min_A_dimensions2: 0.1 max_A_dimensions2: 92.5
min_B_dimensions2: 0.1 max_B_dimensions2: 200.0

min_A_dimensions3: 0.01 max_A_dimensions3: 36.0
min_B_dimensions3: 0.1 max_B_dimensions3: 170.0

In [17]:
# Explore m_data

# Output the distinct brand sim value of matched pairs
min_brand_sim=1
brandSim_to_brandValue={}
for index, row in m_data.iterrows():
    idWalmart,idAmazon=row['idWalmart'],row['idAmazon']
    brandSim=row['brand_brand_jac_qgm_3_qgm_3']
    brandValue=(A.iloc[int(idWalmart)-1]['brand'],B.iloc[int(idAmazon)-1]['brand'])
    if brandSim not in brandSim_to_brandValue:
        brandSim_to_brandValue[brandSim]=[brandValue]
        if brandSim<min_brand_sim:
            min_brand_sim=brandSim
    else:
        if brandValue not in brandSim_to_brandValue[brandSim]:
            brandSim_to_brandValue[brandSim].append(brandValue)
# print(brandSim_to_brandValue)
print('min_brand_sim:{}, len(brandSim_to_brandValue):{}\n'.format(min_brand_sim,len(brandSim_to_brandValue)))
f=open('variables/brandSim_to_brandValue.dict','wb')
pickle.dump(brandSim_to_brandValue,f)
f.close()


# Output the distinct modelno sim value of matched pairs
min_modelno_sim=1
modelnoSim_to_modelnoValue={}
for index, row in m_data.iterrows():
    idWalmart,idAmazon=row['idWalmart'],row['idAmazon']
    modelnoSim=row['modelno_modelno_jac_qgm_3_qgm_3']
    modelnoValue=(A.iloc[int(idWalmart)-1]['modelno'],B.iloc[int(idAmazon)-1]['modelno'])
    if modelnoSim not in modelnoSim_to_modelnoValue:
        modelnoSim_to_modelnoValue[modelnoSim]=[modelnoValue]
        if modelnoSim<min_modelno_sim:
            min_modelno_sim=modelnoSim
    else:
        if modelnoValue not in modelnoSim_to_modelnoValue[modelnoSim]:
            modelnoSim_to_modelnoValue[modelnoSim].append(modelnoValue)
# print(modelnoSim_to_modelnoValue)
print('min_modelno_sim:{}, len(modelnoSim_to_modelnoValue):{}\n'.format(min_modelno_sim,len(modelnoSim_to_modelnoValue)))
f=open('variables/modelnoSim_to_modelnoValue.dict','wb')
pickle.dump(modelnoSim_to_modelnoValue,f)
f.close()

min_brand_sim:0.0, len(brandSim_to_brandValue):50

min_modelno_sim:0.0, len(modelnoSim_to_modelnoValue):64

In [25]:
# Explore u_data

# Output the max brand sim value of unmatched pairs
max_brand_sim=0
unmatched_brandSim_to_brandValue={}
for index, row in u_data.iterrows():
    if index%10000==0:
        print(index,end=' ')
    idWalmart,idAmazon=row['idWalmart'],row['idAmazon']
    brandSim=row['brand_brand_jac_qgm_3_qgm_3']
    brandSim_delta=float(str(brandSim)[:3])
    brand_walmart, brand_amazon=A.iloc[int(idWalmart)-1]['brand'],B.iloc[int(idAmazon)-1]['brand']
    brandValue=(brand_walmart,brand_amazon)
    if brandSim_delta not in unmatched_brandSim_to_brandValue:
        unmatched_brandSim_to_brandValue[brandSim_delta]=[brandValue]
        if brand_walmart and brand_amazon and brandSim>max_brand_sim:
            max_brand_sim=brandSim
            print('idWalmart:{}, idAmazon:{}, brand_brand_jac_qgm_3_qgm_3:{}'.format(row['idWalmart'], row['idAmazon'], row['brand_brand_jac_qgm_3_qgm_3']))
    else:
        if len(unmatched_brandSim_to_brandValue[brandSim_delta])<10000 and brandValue not in unmatched_brandSim_to_brandValue[brandSim_delta]:
            unmatched_brandSim_to_brandValue[brandSim_delta].append(brandValue)
print('max_brand_sim:{}, len(unmatched_brandSim_to_brandValue):{}\n'.format(max_brand_sim,len(unmatched_brandSim_to_brandValue)))
f=open('variables/unmatched_brandSim_to_brandValue.dict','wb')
pickle.dump(unmatched_brandSim_to_brandValue,f)
f.close()

# Output the max modelno sim value of unmatched pairs
max_modelno_sim=0
unmatched_modelnoSim_to_modelnoValue={}
for index, row in u_data.iterrows():
    if index%10000==0:
        print(index,end=' ')
    idWalmart,idAmazon=row['idWalmart'],row['idAmazon']
    modelnoSim=row['modelno_modelno_jac_qgm_3_qgm_3']
    modelnoSim_delta=float(str(modelnoSim)[:3])
    modelno_walmart, modelno_amazon=A.iloc[int(idWalmart)-1]['modelno'],B.iloc[int(idAmazon)-1]['modelno']
    modelnoValue=(modelno_walmart,modelno_amazon)
    if modelnoSim_delta not in unmatched_modelnoSim_to_modelnoValue:
        unmatched_modelnoSim_to_modelnoValue[modelnoSim_delta]=[modelnoValue]
        if modelno_walmart and modelno_amazon and modelnoSim>max_modelno_sim:
            max_modelno_sim=modelnoSim
            print('idWalmart:{}, idAmazon:{}, modelno_modelno_jac_qgm_3_qgm_3:{}'.format(row['idWalmart'], row['idAmazon'], row['modelno_modelno_jac_qgm_3_qgm_3']))
    else:
        if len(unmatched_modelnoSim_to_modelnoValue[modelnoSim_delta])<10000 and modelnoValue not in unmatched_modelnoSim_to_modelnoValue[modelnoSim_delta]:
            unmatched_modelnoSim_to_modelnoValue[modelnoSim_delta].append(modelnoValue)
print('max_modelno_sim:{}, len(unmatched_modelnoSim_to_modelnoValue):{}\n'.format(max_modelno_sim,len(unmatched_modelnoSim_to_modelnoValue)))
f=open('variables/unmatched_modelnoSim_to_modelnoValue.dict','wb')
pickle.dump(unmatched_modelnoSim_to_modelnoValue,f)
f.close()


# Output the max title sim value of unmatched pairs
max_title_sim=0
for index, row in u_data.iterrows():
    if index%10000==0:
        print(index,end=' ')
    idWalmart,idAmazon=row['idWalmart'],row['idAmazon']
    title_walmart, title_amazon=A.iloc[int(idWalmart)-1]['title'],B.iloc[int(idAmazon)-1]['title']
    if title_walmart and title_amazon and row['title_title_jac_qgm_3_qgm_3']>max_title_sim:
        max_title_sim=row['title_title_jac_qgm_3_qgm_3']
        print('idWalmart:{}, idAmazon:{}, title_title_jac_qgm_3_qgm_3:{}'.format(row['idWalmart'], row['idAmazon'], row['title_title_jac_qgm_3_qgm_3']))
print('max_title_sim:{}\n'.format(max_title_sim))

0 idWalmart:1.0, idAmazon:976.0, brand_brand_jac_qgm_3_qgm_3:0.0625
idWalmart:1.0, idAmazon:1113.0, brand_brand_jac_qgm_3_qgm_3:1.0
10000 20000 30000 40000 50000 60000 70000 80000 90000 100000 110000 120000 130000 140000 150000 160000 170000 180000 190000 200000 210000 220000 230000 240000 250000 260000 270000 280000 290000 300000 310000 320000 330000 340000 350000 360000 370000 380000 390000 400000 410000 420000 430000 440000 450000 460000 470000 480000 490000 500000 510000 520000 530000 540000 550000 560000 570000 580000 590000 600000 610000 620000 630000 640000 650000 660000 670000 680000 690000 700000 710000 720000 730000 740000 750000 760000 770000 780000 790000 800000 810000 820000 830000 840000 850000 860000 870000 880000 890000 900000 910000 920000 930000 940000 950000 960000 970000 980000 990000 1000000 1010000 1020000 1030000 1050000 1060000 1070000 1080000 1090000 1100000 1110000 1120000 1130000 1140000 1150000 1160000 1170000 1180000 1190000 1200000 1210000 1220000 1230000 1240000 1250000 1260000 1270000 1280000 1290000 1300000 1310000 max_brand_sim:1.0, len(unmatched_brandSim_to_brandValue):10

0 idWalmart:1.0, idAmazon:18638.0, modelno_modelno_jac_qgm_3_qgm_3:0.2307692307692308
idWalmart:2.0, idAmazon:5115.0, modelno_modelno_jac_qgm_3_qgm_3:0.38461538461538464
idWalmart:2.0, idAmazon:13162.0, modelno_modelno_jac_qgm_3_qgm_3:0.5
idWalmart:17.0, idAmazon:15184.0, modelno_modelno_jac_qgm_3_qgm_3:0.6
10000 20000 30000 40000 50000 60000 70000 80000 90000 100000 110000 120000 idWalmart:244.0, idAmazon:13748.0, modelno_modelno_jac_qgm_3_qgm_3:0.7
130000 140000 150000 160000 170000 180000 190000 200000 210000 220000 230000 240000 250000 260000 270000 280000 290000 300000 310000 320000 330000 340000 350000 360000 370000 380000 390000 400000 410000 420000 430000 440000 450000 460000 470000 480000 490000 500000 510000 520000 530000 540000 550000 560000 570000 580000 590000 600000 610000 620000 630000 640000 650000 660000 670000 680000 690000 700000 710000 720000 730000 740000 750000 760000 770000 780000 790000 800000 810000 820000 830000 840000 850000 860000 870000 880000 890000 900000 910000 920000 930000 940000 950000 960000 970000 980000 990000 1000000 1010000 1020000 1030000 1050000 1060000 1070000 1080000 1090000 1100000 1110000 1120000 1130000 1140000 1150000 1160000 1170000 1180000 1190000 1200000 1210000 1220000 1230000 1240000 1250000 1260000 1270000 1280000 1290000 1300000 1310000 max_modelno_sim:0.7, len(unmatched_modelnoSim_to_modelnoValue):9

0 idWalmart:1.0, idAmazon:976.0, title_title_jac_qgm_3_qgm_3:0.1625
idWalmart:1.0, idAmazon:2990.0, title_title_jac_qgm_3_qgm_3:0.19402985074626866
idWalmart:1.0, idAmazon:4408.0, title_title_jac_qgm_3_qgm_3:0.25
idWalmart:2.0, idAmazon:7148.0, title_title_jac_qgm_3_qgm_3:0.4520547945205479
idWalmart:2.0, idAmazon:16721.0, title_title_jac_qgm_3_qgm_3:0.4927536231884058
idWalmart:7.0, idAmazon:3048.0, title_title_jac_qgm_3_qgm_3:0.5
idWalmart:15.0, idAmazon:1700.0, title_title_jac_qgm_3_qgm_3:0.5538461538461539
10000 idWalmart:23.0, idAmazon:17392.0, title_title_jac_qgm_3_qgm_3:0.5576923076923077
idWalmart:23.0, idAmazon:17883.0, title_title_jac_qgm_3_qgm_3:0.6966292134831461
20000 idWalmart:54.0, idAmazon:9735.0, title_title_jac_qgm_3_qgm_3:0.7468354430379747
30000 40000 50000 60000 70000 idWalmart:167.0, idAmazon:12782.0, title_title_jac_qgm_3_qgm_3:0.7976190476190477
80000 90000 100000 110000 120000 130000 140000 150000 160000 idWalmart:325.0, idAmazon:19774.0, title_title_jac_qgm_3_qgm_3:0.8362068965517241
idWalmart:341.0, idAmazon:18623.0, title_title_jac_qgm_3_qgm_3:0.8813559322033898
170000 180000 190000 200000 210000 220000 230000 240000 250000 260000 270000 280000 290000 300000 310000 320000 330000 340000 350000 360000 370000 380000 390000 400000 410000 420000 430000 440000 450000 460000 470000 480000 490000 500000 510000 520000 530000 540000 550000 560000 570000 580000 idWalmart:1130.0, idAmazon:8644.0, title_title_jac_qgm_3_qgm_3:0.9112903225806452
590000 600000 idWalmart:1156.0, idAmazon:10922.0, title_title_jac_qgm_3_qgm_3:0.9428571428571428
610000 620000 630000 640000 650000 660000 670000 680000 690000 700000 710000 720000 730000 740000 750000 760000 770000 780000 790000 800000 810000 820000 830000 840000 850000 860000 870000 880000 890000 900000 910000 920000 930000 940000 950000 960000 970000 980000 990000 1000000 1010000 1020000 1030000 1050000 1060000 1070000 1080000 1090000 1100000 1110000 1120000 1130000 1140000 1150000 1160000 1170000 1180000 1190000 1200000 1210000 1220000 1230000 1240000 1250000 1260000 1270000 1280000 1290000 1300000 1310000 max_title_sim:0.9428571428571428

In [29]:
for brandSim in unmatched_brandSim_to_brandValue:
    print(brandSim,len(unmatched_brandSim_to_brandValue[brandSim]))
for modelnoSim in unmatched_modelnoSim_to_modelnoValue:
    print(modelnoSim,len(unmatched_modelnoSim_to_modelnoValue[modelnoSim]))

0.0 10000
1.0 394
0.2 519
0.5 43
0.4 161
0.1 1838
0.3 312
0.6 8
0.7 4
0.8 2
0.0 10000
0.2 8643
0.1 10000
0.3 2727
0.5 706
0.4 1207
0.6 252
1.0 7
0.7 19

In [7]:
import pandas as pd

# Generate product.csv by concating knowledge base/buy.csv+googleproducts.csv
def file_to_lower(file_name):
    lower_file_name=file_name[:-4]+'_lower.csv'
    file=open(file_name)
    lower_file=open(lower_file_name,'w')
    line=file.readline()
    while line:
        lower_file.write(line.lower())
        line=file.readline()
    file.close()
    lower_file.close()
    
file_to_lower('csv_files/knowledge base/best_buy.csv')
file_to_lower('csv_files/knowledge base/Buy.csv')
file_to_lower('csv_files/knowledge base/GoogleProducts.csv')

best=pd.read_csv('csv_files/knowledge base/best_buy_lower.csv')
buy=pd.read_csv('csv_files/knowledge base/Buy_lower.csv')
google=pd.read_csv('csv_files/knowledge base/GoogleProducts_lower.csv')

product=open('csv_files/product.csv','w')
product.write('title,price,descr\n')

def deal_with_price(s):
    if type(s)==float:
        return s
    tmp=[]
    for c in s:
        if c=='.' or (c>='0' and c<='9'):
            tmp.append(c)
    return float(''.join(tmp))

for index, row in best.iterrows():
    product.write('"{}",{},"{}"\n'.format(row['name'],deal_with_price(row['price']),row['description']))
for index, row in buy.iterrows():
    product.write('"{}",{},"{}"\n'.format(row['name'],deal_with_price(row['price']),row['description']))
for index, row in google.iterrows():
    product.write('"{}",{},"{}"\n'.format(row['name'],deal_with_price(row['price']),row['description']))
    
product.close()

In [3]:
import pandas as pd
product=open('csv_files/product.csv','a+')
amazon=pd.read_csv('csv_files/amazon_cleaned.csv')
for index, row in amazon.iterrows():
    product.write('"{}",{},"{}"\n'.format(row['title'],row['price'],row['descr']))
product.close()

In [1]:
'{},{}'.format(0.43,[1,2,3,4,100])

'0.43,[1, 2, 3, 4, 100]'